version: '3'
services:
    uaa-app:
        image: uaa
        environment:
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://$${eden.spring.security.user.username}:$${eden.spring.security.user.password}@uaa-registry:8761/eureka
            - JAVA_OPTIONS=-Xmx512m -Xms256m
            - RUN_SLEEP=30
            - SPRING_PROFILES_ACTIVE=prod
        ports:
            - 8761:8761
    uaa-kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    uaa-registry:
        extends:
            file: registry.yml
            service: registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_SEARCH_LOCATIONS=file:./central-config/docker-config/
    uaa-zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
