eden:
    security:
        oauth2:
            authorization:
                server:
                    enabled: true
            resource:
                server:
                    enabled: true

eureka:
    client:
        enabled: true
        fetch-registry: true
        healthcheck:
            enabled: true
        register-with-eureka: true
    instance:
        appname: ${spring.application.name}
        health-check-url-path: ${management.endpoints.web.base-path}/health
        home-page-url-path:
        instanceId: ${spring.application.name}.${spring.application.instance-id:${random.value}}
        metadata-map:
            instanceId: ${eureka.instance.instanceId}
            profile: ${spring.profiles.active}
            version: #project.version#
            zone: primary
        prefer-ip-address: true
        status-page-url-path: ${management.endpoints.web.base-path}/info

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 5000

ribbon:
    eureka:
        enabled: true

security:
    oauth2:
        resource:
            filter-order: 3

server:
    servlet:
        session:
            cookie:
                http-only: true

spring:
    application:
        name: #project.name#
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            indent-output: true
        time-zone: GMT+8
    jmx:
        default-domain: ${spring.application.name}
    jpa:
        hibernate:
            ddl-auto: none
        naming:
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_second_level_cache: false
                    use_query_cache: false
                    use_minimal_puts: true
                    hazelcast.instance_name: ${spring.application.name}
                    hazelcast.use_lite_member: true
                ejb:
                    entitymanager_factory_name: ${spring.application.name}
                id:
                    new_generator_mappings: true
                region:
                    factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
    profiles:
        active: #spring.profiles.active#
        include: #spring.profiles.include#
