application:
  user:
    remove-not-activated-amount: -3

eden:
  integration:
    logstash:
      enabled: false
  security:
    oauth2:
      authorization:
        access-token-uri: http://uaa/oauth/token
        access-token-uri-service-id: uaa
        client-credentials:
          client-id: internal
          client-secret: internal
        password:
          client-id: webclient
          client-secret: webclient
        public-token-key-uri: http://uaa/oauth/token_key
        public-token-key-uri-service-id: uaa
      key-store:
        name: keystore.jks
        password: keystore
        alias: uaa

eureka:
  client:
    instance-info-replication-interval-seconds: 10
    metadata:
      user:
        name: ${eden.spring.security.user.name}
        password: ${eden.spring.security.user.password}
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  file:
    name: target/${spring.application.name}.log
  level:
    ROOT: WARN
    org.ylzl.eden: INFO

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/#project.name#?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: eden
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
  liquibase:
    contexts: prod
  thymeleaf:
    cache: true
