version: '3'
services:
    registry:
        image: eden/registry:2.0.0.RELEASE
        volumes:
            - ./central-server-config:/central-config
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod
            - EDEN_SECURITY_USER_NAME=admin
            - EDEN_SECURITY_USER_PASSWORD=21232f297a57a5a743894a0e4a801fc3
            - SPRING_CLOUD_CONFIG_SERVER_SEARCH_LOCATIONS=file:./central-config/localhost-config/
        ports:
            - 8761:8761
