eden:
  integration:
    logstash:
      enabled: false
    swagger:
      default-include-pattern: /(api|oauth|${management.endpoints.web.base-path})/.*
      title: #project.description#
      version: #project.version#
  security:
    oauth2:
      authorization:
        access-token-uri: http://uaa/oauth/token
        access-token-uri-service-id: uaa
        client-credentials:
          client-id: internal
          client-secret: internal
        password:
          client-id: webclient
          client-secret: webclient
        public-token-key-uri: http://uaa/oauth/token_key
        public-token-key-uri-service-id: uaa

eureka:
  client:
    instance-info-replication-interval-seconds: 10
    metadata:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  file:
    name: target/${spring.application.name}.log
  level:
    ROOT: INFO
    org.ylzl.eden: DEBUG

server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://localhost:9411
    enabled: false

zuul:
  host:
    max-per-route-connections: 100
    max-total-connections: 1000
  semaphore:
    max-semaphores: 500
