eden:
    integration:
        logstash:
            enabled: true
    security:
        oauth2:
            authorization:
                access-token-uri: http://uaa/oauth/token
                access-token-uri-service-id: uaa
                client-credentials:
                    client-id: client
                    client-secret: client
                password:
                    client-id: password
                    client-secret: password
                public-token-key-uri: http://uaa/oauth/token_key
                public-token-key-uri-service-id: uaa

eureka:
    client:
        instance-info-replication-interval-seconds: 10
        metadata:
            user:
                name: ${spring.security.user.name}
                password: ${spring.security.user.password}
        registry-fetch-interval-seconds: 10
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10

logging:
    file: target/${spring.application.name}.log
    level:
        ROOT: WARN
        org.ylzl.eden: INFO

security:
    user:
        name: admin
        password: 21232f297a57a5a743894a0e4a801fc3
        roles: ADMIN

server:
    port: 8080

spring:
    zipkin:
        base-url: http://localhost:9411
        enabled: true

zuul:
    host:
        max-per-route-connections: 100
        max-total-connections: 1000
    semaphore:
        max-semaphores: 500
